name: Daily Heartbeat
on:
  push:
      branches:
            - main #run automatically when I push to main 
              workflow_dispatch: # This allows me to run it manually for testing

              jobs:
                build:
                    runs-on: ubuntu-latest
                        steps:
                              - name: Checkout code
                                      uses: actions/checkout@v4

                                            - name: Run heartbeat script
                                                    run: python heartbeat.py

                                                          - name: commit ad push changes
                                                                run: |
                                                                         git config --global user.name "github-actions[bot]"
                                                                                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                                                                                            git add pulse.txt
                                                                                                  git commit -m "chore: update heartbeat pulse" || exit 0
                                                                                                        git push